Помощь друга
htmlacademy-javascript/1655405-kekstagram-24 pull request #9
Opened 2021-10-29 09:06 UTC by yusoro

---
:mortar_board: [Помощь друга](https://up.htmlacademy.ru/javascript/24/user/1655405/tasks/18)

:boom: https://htmlacademy-javascript.github.io/1655405-kekstagram-24/9/

2021-10-29 18:57 UTC, Spearance requested changes

2021-10-29 18:57 UTC, Spearance commented on js/form.js
> +    imagePreview.style.filter = `grayscale(${value})`;
тут не хватает расчетных значений из ТЗ

2021-10-29 18:57 UTC, Spearance commented on js/form.js
> +  scaleControlSmaller.addEventListener('click', () => {
громоздко получилось, нужно попробовать математическим функциями

2021-10-29 18:57 UTC, Spearance commented on js/form.js
> +    if (evt.target.value === 'marvin') {
тут либо switch стоит попробовать, а еще лучше посмотреть в летучке

2021-10-30 13:29 UTC, yusoro commented
Если я меняю значение на то, как в летучке вы показывали (imagePreview.style.filter = `sepia(${parseInt(value, 10) * 0.01})`;) у меня все ломается. И как-то неправильно передается эффект. У меня же меняются настройки слайдера при переключении эффекта. Почему так как у меня нельзя? Все же работает.

2021-11-01 06:05 UTC, Spearance commented on index.html
> +  <script src="nouislider/nouislider.js"></script>
лучше его поставить до main.js

2021-11-01 06:06 UTC, Spearance commented on js/form.js
> +      currentEffect = 'none';
не сбрасывается измененный размер у картинки

2021-11-01 06:31 UTC, merged